name: bamlib
description: A library of dart helpers.  Not really meant for anyone else (yet,) but feel free to use if you should find helpful.
version: 0.5.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
